21 lines (14 sloc)  378 Bytes

### live server test 

GET http://localhost:8000


## ==================== Admin registration and login

### Admin user register 

POST http://localhost:8000/api/v1/registerloginRouter
Content-Type: application/json

{
    
    "lName": "Shrestha",
    "Dob": "2020-02-20",
    "phone":"044444444",
    "email": "asdfasdf@gmail.com",
    "address": "Sydney",
    "password": "12345"
}

### Admin login

POST http://localhost:8000/login
Content-Type: application/json

{
    
    "email": "bibekheores@gmail.com",
    "password": "Bibek"
}

### post category
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"active",
    "name":"Sportsasdf",
    "parentCatId":null
} 

### delete category
DELETE  http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "ids": ["62c8c58bd9d7ef391158ce94"]
} 


### get payment method

GET http://localhost:8000/api/v1/payment-method

### post payment method
POST http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "status":"active",
    "name":"Rice",
    "desc":"Check check check"
}
### put payment method
PUT http://localhost:8000/api/v1/payment-method
Content-Type: application/json

{
    "_id": "62d1ff0c6a5ef149b414a06f",
    "status":"inactive",
    "name":"Debit",
    "desc":"ibiebbaisdbf"
}

### delete payment method
DELETE http://localhost:8000/api/v1/payment-method/62d1ff0c6a5ef149b414a06f